### ISSUE TITLE
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true

### ISSUE THREAD

**Issue by llorcasantana** [JesusBetaX/restlight#1]
Hola, es el mejor código que he visto en la red, pero no he podido hecharlo a andar. Cada vez que ejecuto me sale este error,

D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true

He probado con un script mas directo para saber si es el telefono pero ese si me sale el resultado que quiero.

Tengo que hacer algo  adicional?? gracias

**Comment by JesusBetaX** [comment]
Debes agregar estos permisos en el archivo manifiesto:
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

Para mayor información puedes consultar aqui: https://developer.android.com/training/basics/network-ops/connecting
